/* The labeled simulator, hosted server-side so the door can be walked with a
   board behind it. Every payload it emits carries origin 'DEMO' and the client
   renders the badge. It is NOT the engine; it is the shape of one.

   Quotes come from the simulator's current board so a LOCK written against a
   demo quote is recorded (durably, in the ledger) with origin DEMO and a
   modelVersion that says so. The simulator publishes NO outcomes, so demo
   locks never settle — resolve() is null. A simulated WIN would be a lie. */
import { DemoDataSource } from '../../services/mock/demoProvider.ts';
import type { EngineQuote, EngineResolution, EngineSource } from './EngineSource.ts';
import type { ArenaSnapshot, ScanInput, ScanProgress, ScanResult } from '../../types/index.ts';

export class DemoEngine implements EngineSource {
  readonly label = 'DEMO SIMULATOR (server-hosted)';
  readonly origin = 'DEMO' as const;
  private inner = new DemoDataSource();
  load(): Promise<ArenaSnapshot> { return this.inner.load(); }
  subscribe(onSnapshot: (s: ArenaSnapshot) => void): () => void { return this.inner.subscribe(onSnapshot); }

  async quote(marketId: string): Promise<EngineQuote | null> {
    const snap = await this.inner.load();
    const m = snap.markets.find((x) => x.id === marketId);
    if (!m) return null;
    const ref = m.venueRefs[0] ?? null;
    return {
      marketId: m.id, marketTitle: m.title, venue: ref?.venue ?? null, venueMarketId: ref?.venueMarketId ?? null,
      marketBps: m.marketProbabilityBps, vixyBps: m.vixyProbabilityBps, confidenceBps: m.confidenceBps, reversalRiskBps: m.reversalRiskBps,
      modelVersion: 'demo-simulator (not a model)', evidence: ['SIMULATED: prices and probabilities are generated by the demo simulator'],
      rationale: null, inputs: null, dataAgeMs: null,
      closesAt: m.closesAt, origin: 'DEMO', quotedAt: new Date().toISOString(),
    };
  }

  async resolve(_marketId: string): Promise<EngineResolution | null> { return null; }

  scanMarket(_userId: string, input: ScanInput, onProgress?: (p: ScanProgress) => void): Promise<ScanResult> { return this.inner.scanMarket(input, onProgress); }
}
